### ISSUE TITLE
macOS version error (with 2.1.0)

### ISSUE THREAD

**Issue by remy** [mattpannella/pocket_core_autoupdate_net#24]
I ran the pocket_updater that was previously on 1.4.0 and it crashed out ending with this:

```
....
Starting Repo: openfpga-tecmo
v2.0 is the most recent release, checking local core...
local core found: v2.0.0
Looking for BIOS
Downloading gemini.rom
Unhandled exception. System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at pannella.analoguepocket.HttpHelper.DownloadFileAsync(String uri, String outputPath)
   at pannella.analoguepocket.PocketCoreUpdater.SetupBios(Bios bios)
   at pannella.analoguepocket.PocketCoreUpdater.RunUpdates()
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)
[1]    59579 abort      ./pocket_updater
```

[Full log here](https://gist.github.com/remy/48aceb501b1cc0a8a0764d1325939a8d)

So I downloaded the latest release (2.1.0) and put it on the pocket's SD card, and now it crashes immediately:

```
Analogue Pocket Core Updater v2.1.0
Checking for updates...
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at pannella.analoguepocket.SettingsManager..ctor(String settingsPath, List`1 cores)
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)
[1]    61299 abort      ./pocket_updater
```

Any ideas?

**Comment by mattpannella** [comment]
hm, try deleting your pocket_updater_settings.json file and run it again

**Comment by remy** [comment]
That did the trick 👍
