### ISSUE TITLE
dmg_bios.bin download fails if you don't already have the GB core installed

### ISSUE THREAD

**Issue by codewario** [mattpannella/pocket_core_autoupdate_net#4]
It appears that it doesn't try to create the directory first if the core hasn't been installed previously. Once I installed the GB core manually the updater script was able to install the other cores without issue (though I already had the GBC core so not sure if the same issue affects that installation as well).

Here is the program output from before I installed the Spiritualized1997 GB core manually:

```
Analogue Pocket Core Updater v1.3.0
Checking for updates...
Download master cores list file from github? (This will overwrite your current file) [y/n]:
yDownloading...
Download complete:
D:\/auto_update.json
Starting update process...
Starting Repo: openFPGA-GBA
v1.2.0 is the most recent release, checking local core...
local core found: v1.2.0
Looking for BIOS
BIOS file already installed: gba_bios.bin
Up to date. Skipping core
------------
Starting Repo: openFPGA-GB-GBC
v1.3.0 is the most recent release, checking local core...
local core found: v1.3.0
Looking for BIOS
BIOS file already installed: gbc_bios.bin
Downloading dmg_bios.bin
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\assets\gb\common\dmg_bios.bin'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at pannella.analoguepocket.HttpHelper.DownloadFileAsync(String uri, String outputPath)
   at pannella.analoguepocket.PocketCoreUpdater.SetupBios(Bios bios)
   at pannella.analoguepocket.PocketCoreUpdater.RunUpdates()
   at Program.Main(String[] args)
   at Program.<Main>(String[] args)
```

**Comment by mattpannella** [comment]
hey thanks for this, it's a side effect of the gb core not being properly installed after they split gb and gbc into separate releases. I'll fix it soon

**Comment by fith** [comment]
Just hit this on 1.4.

I just created the directories and it worked after that.

**Comment by mattpannella** [comment]
yeah that will fix it. sorry I haven't gotten around to this yet. but it's relatively quick to clean up. thanks!

**Comment by davewongillies** [comment]
2.0.1 seems to have resolved this issue
